baseURL = 'https://your-site-domain.com/'
languageCode = 'en-us'
title = 'Default Site Title'

paginate = "10" # Number of posts per page
#googleAnalytics = "G-your-google-analytics-tag"

[Author] # Used in authorbox
name = "Author Name"
bio = "Author bio. Lorem ipsum dolor sit amet."
image = "/img/author.jpg"

[Menu]
[[Menu.main]]
name = "Home"
url = "/"
weight = 1
[[Menu.main]]
name = "Posts"
url = "/posts/"
weight = 2
[[Menu.main]]
name = "About"
url = "/about/"
weight = 3
[[Menu.main]]
name = "Contact"
url = "/contact/"
weight = 4

[Params]
globalAdvisory = true # My own custom parameter
readmore = true # Show "Read more" button in list if true
authorbox = true # Show authorbox at bottom of pages if true
mainSections = ["post"] # Specify section pages to show on home page and the "Recent articles" widget
dateformat = "2006-01-02" # Change the format of dates, not currently used

[Params.logo]
image = "/img/logo.png"
